import pandas as pd
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)

D = "/home/claude/hackathon/project/data/"

def sep(title):
    print("\n" + "="*90)
    print(title)
    print("="*90)

# ---------- Details ----------
details = pd.read_csv(D+"Details_Itapema.csv", dtype={"airbnb_listing_id": str, "owner_id": str})
sep("DETAILS - shape / dtypes")
print(details.shape)
sep("DETAILS - nulls (%)")
print((details.isna().mean()*100).round(1).sort_values(ascending=False))
sep("DETAILS - duplicated airbnb_listing_id")
print(details["airbnb_listing_id"].duplicated().sum())
sep("DETAILS - listing_type value_counts")
print(details["listing_type"].value_counts(dropna=False))
sep("DETAILS - number_of_bedrooms value_counts")
print(details["number_of_bedrooms"].value_counts(dropna=False).sort_index())
sep("DETAILS - number_of_bathrooms describe")
print(details["number_of_bathrooms"].describe())
sep("DETAILS - star_rating describe + zero count")
print(details["star_rating"].describe())
print("star_rating == 0:", (details["star_rating"]==0).sum(), "of", len(details))
sep("DETAILS - number_of_reviews describe + zero count")
print(details["number_of_reviews"].describe())
print("number_of_reviews == 0:", (details["number_of_reviews"]==0).sum())
sep("DETAILS - is_professional / can_instant_book / is_new_listing / is_guest_favorite")
for c in ["is_professional","can_instant_book","is_new_listing","is_guest_favorite"]:
    print(c, details[c].value_counts(dropna=False).to_dict())
sep("DETAILS - aquisition_date range")
details["aquisition_date"] = pd.to_datetime(details["aquisition_date"], errors="coerce")
print(details["aquisition_date"].min(), "->", details["aquisition_date"].max())
sep("DETAILS - number_of_guests / min_nights describe")
print(details[["number_of_guests","min_nights","cleaning_fee"]].describe())

# ---------- Hosts ----------
hosts = pd.read_csv(D+"Hosts_ids_Itapema.csv", dtype={"owner_id": str})
sep("HOSTS - shape / dtypes")
print(hosts.shape)
sep("HOSTS - nulls (%)")
print((hosts.isna().mean()*100).round(1).sort_values(ascending=False))
sep("HOSTS - duplicated owner_id")
print(hosts["owner_id"].duplicated().sum())
sep("HOSTS - is_superhost / is_verified")
print(hosts["is_superhost"].value_counts(dropna=False))
print(hosts["is_verified"].value_counts(dropna=False))
sep("HOSTS - years_host describe")
print(hosts["years_host"].describe())

# ---------- Mesh ----------
mesh = pd.read_csv(D+"Mesh_Ids_Data_Itapema.csv", dtype={"airbnb_listing_id": str})
sep("MESH - shape")
print(mesh.shape)
sep("MESH - duplicated airbnb_listing_id")
print(mesh["airbnb_listing_id"].duplicated().sum())
sep("MESH - suburb value_counts")
print(mesh["suburb"].value_counts(dropna=False))
sep("MESH - country/state/city uniques")
print(mesh["country"].unique(), mesh["state"].unique(), mesh["city"].unique())
sep("MESH - lat/long describe")
print(mesh[["latitude","longitude"]].describe())

# ---------- Price_AV ----------
price = pd.read_csv(D+"Price_AV_Itapema.csv", dtype={"airbnb_listing_id": str})
sep("PRICE_AV - shape")
print(price.shape)
sep("PRICE_AV - unique listings")
print(price["airbnb_listing_id"].nunique())
sep("PRICE_AV - rows per listing describe")
print(price.groupby("airbnb_listing_id").size().describe())
sep("PRICE_AV - duplicated (listing,date) rows")
print(price.duplicated(subset=["airbnb_listing_id","date"]).sum())
price["date"] = pd.to_datetime(price["date"], errors="coerce")
sep("PRICE_AV - date range (stay date)")
print(price["date"].min(), "->", price["date"].max())
price["aquisition_date"] = pd.to_datetime(price["aquisition_date"], errors="coerce")
sep("PRICE_AV - aquisition_date (capture date) range")
print(price["aquisition_date"].min(), "->", price["aquisition_date"].max())
print("unique capture dates:", price["aquisition_date"].dt.date.nunique())
sep("PRICE_AV - price describe")
print(price["price"].describe())
print("price == 0:", (price["price"]==0).sum(), " price null:", price["price"].isna().sum())
sep("PRICE_AV - price by capture date count (sample)")
print(price.groupby(price["aquisition_date"].dt.date).size().head(20))

# ---------- VivaReal ----------
viva = pd.read_csv(D+"VivaReal_Itapema.csv", dtype={"listing_id": str})
sep("VIVAREAL - shape")
print(viva.shape)
sep("VIVAREAL - nulls (%)")
print((viva.isna().mean()*100).round(1).sort_values(ascending=False))
sep("VIVAREAL - duplicated listing_id")
print(viva["listing_id"].duplicated().sum())
sep("VIVAREAL - business_types / listing_type / property_type")
print(viva["business_types"].value_counts(dropna=False))
print(viva["listing_type"].value_counts(dropna=False))
print(viva["property_type"].value_counts(dropna=False))
sep("VIVAREAL - suburb value_counts")
print(viva["suburb"].value_counts(dropna=False))
sep("VIVAREAL - sale_price describe")
print(pd.to_numeric(viva["sale_price"], errors="coerce").describe())
sep("VIVAREAL - bedrooms value_counts")
print(viva["bedrooms"].value_counts(dropna=False).sort_index())

# ---------- Cross-file key coverage ----------
sep("CROSS-CHECK - Details.airbnb_listing_id in Mesh?")
print((details["airbnb_listing_id"].isin(mesh["airbnb_listing_id"])).mean())
sep("CROSS-CHECK - Mesh.airbnb_listing_id in Details?")
print((mesh["airbnb_listing_id"].isin(details["airbnb_listing_id"])).mean())
sep("CROSS-CHECK - Details.airbnb_listing_id in Price_AV?")
print((details["airbnb_listing_id"].isin(price["airbnb_listing_id"])).mean())
sep("CROSS-CHECK - Details.owner_id in Hosts.owner_id?")
print((details["owner_id"].isin(hosts["owner_id"])).mean())
sep("CROSS-CHECK - Hosts.owner_id in Details.owner_id?")
print((hosts["owner_id"].isin(details["owner_id"])).mean())
sep("CROSS-CHECK - VivaReal.suburb vs Mesh.suburb overlap")
print("Mesh suburbs:", sorted(mesh['suburb'].dropna().unique().tolist()))
print("VivaReal suburbs:", sorted(viva['suburb'].dropna().unique().tolist()))
